AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for GatherHub static website with authentication, notification, and storage'

Resources:
  # S3 Bucket for static website hosting
  GatherHubWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-website'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration: # Allow public access
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Bucket policy to allow public read access
  GatherHubWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GatherHubWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref GatherHubWebsiteBucket, '/*']]



  # Cognito User Pool for authentication
  GatherHubUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-user-pool'
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  # Cognito User Pool Client
  GatherHubUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-client'
      UserPoolId: !Ref GatherHubUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  # SNS Topic for user notifications
  GatherHubNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-notifications'


  # DynamoDB Table for storage
  GatherHubStorageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-storage'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

 # S3 Bucket for Lambda code
  LambdaCodeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-lambda-code'
      VersioningConfiguration:
        Status: Enabled  # Optional, but useful for keeping track of Lambda versions
      AccessControl: Private  # Restrict access to the bucket to prevent public access
      
    # Lambda function for event creation
  GatherHubEventCreationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-event-creation'
      Runtime: python3.9
      Handler: index.event_create_handler  # Placeholder handler name, can be updated later
      Role: !GetAtt GatherHubLambdaExecutionRole.Arn
      Timeout: 30  # Set appropriate timeout based on your use case
      Code:
        S3Bucket: !Ref gatherhub-lambda-code  # The S3 bucket containing the zip file with index.py
        S3Key: event_registration_handler/index.zip  # The path to the zip file in the S3 bucket

#   # Lambda function for event update
#   GatherHubEventUpdateFunction:
#     Type: AWS::Lambda::Function
#     Properties:
#       FunctionName: !Sub '${AWS::StackName}-event-update'
#       Runtime: python3.9
#       Handler: index.event_update_handler  # Placeholder handler name, can be updated later
#       Role: !GetAtt GatherHubLambdaExecutionRole.Arn
#       Timeout: 30

#   # Lambda function for user registration for event
#   GatherHubUserRegistrationFunction:
#     Type: AWS::Lambda::Function
#     Properties:
#       FunctionName: !Sub '${AWS::StackName}-user-registration'
#       Runtime: python3.9
#       Handler: index.user_registration_handler  # Placeholder handler name, can be updated later
#       Role: !GetAtt GatherHubLambdaExecutionRole.Arn
#       Timeout: 30

#IAM for Lambda
  GatherHubLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DescribeTable
                  - sns:Publish
                Resource: "*"



Outputs:
  GatherHubWebsiteURL:
    Description: 'URL for the static website'
    Value: !GetAtt GatherHubWebsiteBucket.WebsiteURL
  GatherHubUserPoolId:
    Description: 'ID of the Cognito User Pool'
    Value: !Ref GatherHubUserPool
  GatherHubUserPoolClientId:
    Description: 'ID of the Cognito User Pool Client'
    Value: !Ref GatherHubUserPoolClient
  GatherHubNotificationTopicArn:
    Description: 'ARN of the SNS Topic'
    Value: !Ref GatherHubNotificationTopic
  GatherHubDynamoDBTableName:
    Description: 'Name of the DynamoDB Table'
    Value: !Ref GatherHubStorageTable
