AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for GatherHub static website with authentication, notification, and storage'

Resources:
  # S3 Bucket for static website hosting
  GatherHubWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-website'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration: # Allow public access
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Bucket policy to allow public read access
  GatherHubWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GatherHubWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref GatherHubWebsiteBucket, '/*']]


  # Cognito User Pool for authentication
  GatherHubUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-user-pool'
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  # Cognito User Pool Client
  GatherHubUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-client'
      UserPoolId: !Ref GatherHubUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  # SNS Topic for user notifications
  GatherHubNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-notifications'

  # DynamoDB Table for storage
  GatherHubStorageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-storage'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  GatherHubWebsiteURL:
    Description: 'URL for the static website'
    Value: !GetAtt GatherHubWebsiteBucket.WebsiteURL
  GatherHubUserPoolId:
    Description: 'ID of the Cognito User Pool'
    Value: !Ref GatherHubUserPool
  GatherHubUserPoolClientId:
    Description: 'ID of the Cognito User Pool Client'
    Value: !Ref GatherHubUserPoolClient
  GatherHubNotificationTopicArn:
    Description: 'ARN of the SNS Topic'
    Value: !Ref GatherHubNotificationTopic
  GatherHubDynamoDBTableName:
    Description: 'Name of the DynamoDB Table'
    Value: !Ref GatherHubStorageTable
