Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/kaustubh-htw/GatherHub/blob/main/Infrastructure/gatherhub-S3.yaml
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/kaustubh-htw/GatherHub/blob/main/Infrastructure/cognito.yaml
 
