AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # Nested Stack for Base Resources (S3, Cognito, DynamoDB, SNS)
  BaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/mybucket/base/s3.yaml'  # URL to your S3-hosted template for base resources

 