AWSTemplateFormatVersion: '2010-09-09'

Resources:
  GatherHubFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gatherhub-frontend
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  GatherHubBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GatherHubFrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::gatherhub-frontend/*"
