AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GatherHubUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: GatherHubUserPool
      AliasAttributes:
        - email
        - username
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      MfaConfiguration: OFF
      LambdaConfig: {}

  GatherHubUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: GatherHubWebClient
      UserPoolId: !Ref GatherHubUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      CallbackURLs:
        - 'http://localhost:3000/callback'  # Dummy URL for now
      LogoutURLs:
        - 'http://localhost:3000/logout'    # Dummy URL for now
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile

Outputs:
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref GatherHubUserPool

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref GatherHubUserPoolClient
